<?php

/*
 * This file is part of rrmode/flarum-elasticsearch.
 *
 * Copyright (c) 2021 rrmode.
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Rrmode\FlarumES\Controller;

use Elasticsearch\Client;
use Flarum\Api\Controller\ListDiscussionsController;
use Flarum\Discussion\Filter\DiscussionFilterer;
use Flarum\Discussion\Search\DiscussionSearcher;
use Flarum\Http\UrlGenerator;
use Psr\Http\Message\ServerRequestInterface;
use Rrmode\FlarumES\Service\Index;
use Rrmode\FlarumES\Service\Search;
use Tobscure\JsonApi\Document;

class DiscussionsListController extends ListDiscussionsController
{
    private $index;

    private $search;

    private $client;

    public function __construct(DiscussionFilterer $filterer, DiscussionSearcher $searcher, UrlGenerator $url, Index $index, Search $search, Client $client)
    {
        $this->client = $client;
        $this->search = $search;
        $this->index = $index;
        parent::__construct($filterer, $searcher, $url);
    }

    protected function data(ServerRequestInterface $request, Document $document)
    {

        var_dump($this->search->find('well'));
//        return parent::data($request, $document); // TODO: Change the autogenerated stub
    }
}
